spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service


server:
  port: 8080

---
spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 123123



