spring:
  main:
    web-application-type: reactive

  application:
    name: zuul-edge-server
  profiles:
    active: localhost
  allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service/
          predicates:
            - Path=/api/1.0/product/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 8762
