spring:
  application:
    name: zuul-edge-server
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Zuul Edge Server

---

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
server:
  port: 8762

zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /api/1.0/product/**
      service-id: product-service
      url : http://localhost:8762/api/1.0/product/
      stripPrefix: true