spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: localhost
info:
  component: Product Service

server:
  port: 8080
logging:
  level:
    root: off
    com.eleiatech: DEBUG
---
spring:
  config:
    activate:
      on-profile: localhost  # This is the correct way to activate the "localhost" profile
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 123123

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
